config/routes.rb
Iorder::Application.routes.draw do
 

  devise_for :users
  resources :shops
  resources :groups

  root :to => "shops#index"

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/competition.rb
class Competition < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/shop.rb
class Shop < ActiveRecord::Base
	has_attached_file :menu_image
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  layout "backstage"
  before_action :authenticate_user!
  
  def index
  	@groups = Group.order("id desc")
  end

  def show
  	@group = Group.find(params[:id])

  end

  def new
  	@group = Group.new
  end

  def create
  	@group = Group.new(group_params)
  	if @group.save
  		flash[:warning] = "Success!"
  		redirect_to groups_path
  	else
  		flash[:warning] = "Fail!:#{@group.errors.full_messages}"
  		render :new
  	end

  end

  def edit
  	@group = Group.find(params[:id])
  end

  def update
  	@group = Group.find(params[:id])
  	
  	if @group.update_attributes(group_params)
  		flash[:warning] = "Success!"
  		redirect_to groups_path
  	else	
  		flash[:warning] = "Fail!:#{@group.errors.full_messages}"
  		render :edit
  	end 

  end

  def destroy
  	@group = Group.find(params[:id])
  	@group.destroy
  	redirect_to groups_path
  end

private

	def group_params
		params.require("group").permit(:title, :date, :date)
	end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  layout "backstage"
  before_action :authenticate_user!
  
  def index
  	@shops = Shop.order("id desc")
  end

  def show
  	@shop = Shop.find(params[:id])

  end

  def new
  	@shop = Shop.new
  end

  def create
  	@shop = Shop.new(shop_params)
  	if @shop.save
  		flash[:warning] = "Success!"
  		redirect_to shops_path
  	else
  		flash[:warning] = "Fail!:#{@shop.errors.full_messages}"
  		render :new
  	end

  end

  def edit
  	@shop = Shop.find(params[:id])
  end

  def update
  	@shop = Shop.find(params[:id])
  	
  	if @shop.update_attributes(shop_params)
  		flash[:warning] = "Success!"
  		redirect_to shops_path
  	else	
  		flash[:warning] = "Fail!:#{@shop.errors.full_messages}"
  		render :edit
  	end 

  end

  def destroy
  	@shop = Shop.find(params[:id])
  	@shop.destroy
  	redirect_to shops_path
  end

private

	def shop_params
		params.require("shop").permit(:name, :location, :hours, :menu_image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/groups/edit.html.erb
<h1>Groups#edit</h1>
<p>Find me in app/views/groups/edit.html.erb</p>

app/views/groups/index.html.erb
<p style="text-align: right;">
	<%= link_to "新增開團", new_shop_path, :class => "btn btn-lg btn-primary" %>
</p>
<table class="table">
	<tbody>
		<tr>		
			<th>編號</th>
			<th>名稱</th>
			<th>日期</th>
			<th>更新</th>
			<th>刪除</th>
		</tr>
		<% @groups.each do |group|%>
			<tr>
				<td><%= group.id %></td>
				<td><%= group.tite %></td>	
				<td><%= group.date %></td>	
				<td><%= link_to "查看", group_path(group), :class => "btn btn-info" %></td>
				<td><%= link_to "更新", edit_group_path(group), :class => "btn btn-success"  %></td>
				<td><%= link_to "刪除", group_path(group), method: :delete, data: { :confirm => "確定要刪除嗎?" }, :class => "btn btn-danger"  %></td>
			</tr>
		<% end %>
	<tbody>
</table>

app/views/groups/show.html.erb
<h1>Groups#show</h1>
<p>Find me in app/views/groups/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iorder</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/backstage.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>詹姆士下午茶系統</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"> -->
	<!-- <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css"> -->
	<link rel="stylesheet" href="//bootswatch.com/flatly/bootstrap.min.css">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="body-container">
		    <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">詹姆士下午茶系統</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
                <li><a href="/shops/">餐廳管理</a></li>
                <li><a href="/groups/">出團管理</a></li>
                <li><%= link_to('登出', destroy_user_session_path, :method => :delete) %></li>
                <li><%= link_to('修改密碼', edit_registration_path(:user)) %></li>
              <% else %>
                <li><%= link_to('註冊', new_registration_path(:user)) %></li>
                <li><%= link_to('登入', new_session_path(:user)) %></li>
              <% end %>            
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </div>
      <% if flash[:warning] %>
        <div class="alert fade in alert-success"><a class="close" data-dismiss="alert" href="#">x</a>
          <%= flash[:warning] %>
        </div>
      <% end %>
      <div class="container">
        <%= yield %>
      </div>
	</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/shops/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">新增餐廳</h3>
  </div>
  <div class="panel-body">
		<%= form_for @shop do |f| %>
			<p>
				<%= f.label :name, "名稱" %>
				<%= f.text_field :name, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :location, "地點" %>
				<%= f.text_field :location, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :hours, "營業時間" %>
				<%= f.text_field :hours, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :menu_image, "菜單" %>
				<%= f.file_field :menu_image, :class => "form-control" %>	
				<%= image_tag @shop.menu_image %>
			</p>
			<p>
				<%= f.submit "更新", :class => "btn btn-default"  %>
			</p>
		<% end %>
	</div>
</div>

app/views/shops/index.html.erb
<p style="text-align: right;">
	<%= link_to "新增餐廳", new_shop_path, :class => "btn btn-lg btn-primary" %>
</p>
<table class="table">
	<tbody>
		<tr>		
			<th>編號</th>
			<th>名稱</th>
			<th>地址</th>
			<th>營業時間</th>
			<th>更新</th>
			<th>刪除</th>
		</tr>
		<% @shops.each do |shop|%>
			<tr>
				<td><%= shop.id %></td>
				<td><%= shop.name %></td>	
				<td><%= shop.location %></td>	
				<td><%= shop.hours %></td>
				<td><%= link_to "查看", shop_path(shop), :class => "btn btn-info" %></td>
				<td><%= link_to "更新", edit_shop_path(shop), :class => "btn btn-success"  %></td>
				<td><%= link_to "刪除", shop_path(shop), method: :delete, data: { :confirm => "確定要刪除嗎?" }, :class => "btn btn-danger"  %></td>
			</tr>
		<% end %>
	<tbody>
</table>

app/views/shops/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">新增餐廳</h3>
  </div>
  <div class="panel-body">
		<%= form_for @shop do |f| %>
			<p>
				<%= f.label :name, "名稱" %>
				<%= f.text_field :name, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :location, "地點" %>
				<%= f.text_field :location, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :hours, "營業時間" %>
				<%= f.text_field :hours, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :menu_image, "菜單" %>
				<%= f.file_field :menu_image, :class => "form-control" %>
			</p>
			<p>
				<%= f.submit "新增", :class => "btn btn-default"  %>
			</p>
		<% end %>
	</div>
</div>

app/views/shops/show.html.erb
	
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">餐廳資料</h3>
  </div>
  <div class="panel-body">
		<%= form_for @shop do |f| %>
			<p>
				<%= f.label :name, "名稱" %>
				<%= f.label :name, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :location, "地點" %>
				<%= f.label :location, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :hours, "營業時間" %>
				<%= f.label :hours, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :menu_image, "菜單" %>
				<%= image_tag @shop.menu_image %>
			</p>
				<p><%= link_to "返回", :back, :class => "btn btn-lg btn-primary" %></p>
		<% end %>
	</div>
</div>